--- 
version: "2"
services: 
  kafka: 
    environment: 
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181/kafka"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    image: confluentinc/cp-kafka
    links: 
      - zookeeper
    ports: 
      - 9092:9092
  schema-registry:
    image: confluentinc/cp-schema-registry
    ports:
      - "8081:8081"
    links: 
      - zookeeper
      - kafka
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: "zookeeper:2181/kafka"
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8081
      SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_METHODS: "GET,POST,PUT,OPTIONS"
      SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_ORIGIN: "*"
      KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092
  kafka-connect: 
    environment: 
      CONNECT_BOOTSTRAP_SERVERS: kafka:9092
      CONNECT_GROUP_ID: kafka-connect
      CONNECT_CONFIG_STORAGE_TOPIC: kafka-connect.config
      CONNECT_OFFSET_STORAGE_TOPIC: kafka-connect.offsets
      CONNECT_STATUS_STORAGE_TOPIC: kafka-connect.status
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_KEY_CONVERTER_SCHEMA_ENABLE: "false"
      CONNECT_INTERNAL_VALUE_CONVERTER_SCHEMA_ENABLE: "false"
      CONNECT_REST_ADVERTISED_HOST_NAME: kafka-connect
      CONNECT_ZOOKEEPER_CONNECT: "zookeeper:2181/kafka"
    image: confluentinc/cp-kafka-connect
    links: 
      - zookeeper
      - kafka
      - schema-registry
    ports: 
      - 8083:8083
    volumes:
      - ./kafka-connect/jars:/etc/kafka-connect/jars
      - ~/.aws:/root/.aws
  kafka-connect-ui: 
    environment: 
      CONNECT_URL: "http://kafka-connect:8083"
    image: landoop/kafka-connect-ui
    links: 
      - kafka-connect
    ports:
      - 8000:8000
  zookeeper: 
    image: confluentinc/cp-zookeeper
    ports: 
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  schema-registry-ui:
    environment:
      SCHEMAREGISTRY_URL: "http://schema-registry:8081"
    image: landoop/schema-registry-ui
    links:
      - schema-registry
    ports:
      - 8001:8000
